[NbConvertApp] Converting notebook DC2_Coadd_Run1.1p_direct_access_--_color-color_stellar_locus.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: desc-stack
/global/common/software/lsst/common/miniconda/kernels/stack.sh: illegal option -- f
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 20: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 21: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 22: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 23: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 24: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 25: module: command not found
/global/common/software/lsst/cori-haswell-gcc/stack//setup_current_sims.sh: line 26: module: command not found
Now setup any necessary stack packages such as: setup lsst_distrib or lsst_sims
[NbConvertApp] ERROR | Error while converting 'DC2_Coadd_Run1.1p_direct_access_--_color-color_stellar_locus.ipynb'
Traceback (most recent call last):
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 373, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 171, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 189, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 131, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 308, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 211, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 70, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/common/software/python/3.6-anaconda-4.4/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 242, in preprocess_cell
    raise CellExecutionError(msg)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# https://stackoverflow.com/questions/19390320/scatterplot-contours-in-matplotlib
def bin_kde(x, y, nbins=20, **kwargs):
    from scipy.stats import kde
    k = kde.gaussian_kde(x, y)
    xi, yi = np.mgrid[x.min():x.max():nbins*1j, y.min():y.max():nbis*1j]
    zi = k(np.vstack([xi.flatten(), yi.flatten()]))

# This doesn't exactly work, I've done something wrong here.
xi, yi, zi = bin_kde(stars['g_mag']-stars['r_mag'], stars['r_mag']-stars['i_mag'])
------------------

TypeError: invalid type comparison

